/*
 * 
 */
package br.org.exemplo.ctarefas.view;

import br.org.exemplo.ctarefas.model.Tarefa;
import br.org.exemplo.ctarefas.persistence.BaseDados;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.dizitart.no2.FindOptions;
import org.dizitart.no2.NitriteId;
import org.dizitart.no2.SortOrder;

/**
 *
 * @author Administrador
 */
public class FrmMain extends javax.swing.JFrame {

 private Tarefa tarefa = new Tarefa();
 private List<Tarefa> tarefas;
 private DateTimeFormatter auxFormat = DateTimeFormatter.ofPattern("dd/MM/yyyy");

 private void cancelar() {
  tarefa = new Tarefa();
  txData.setValue("");
  txDescricao.setText("");
 }

 private void salvar() {
  tarefa.setData(txData.getValue().toString());
  tarefa.setDescricao(txDescricao.getText());
  if (tarefa.getId() == null) {
   BaseDados.RTarefa.insert(tarefa);
  } else {
   BaseDados.RTarefa.update(tarefa);
  }
  this.cancelar();
  this.recuperar();
  JOptionPane.showMessageDialog(this, "Registro Salvo");
 }

 private void recuperar() {
  this.tarefas = BaseDados.RTarefa.find(FindOptions.sort("data", SortOrder.Ascending)).toList();
  DefaultTableModel dtm = (DefaultTableModel) tbTarefas.getModel();
  dtm.setRowCount(0);
  this.tarefas.forEach((t) -> {
   dtm.addRow(new Object[]{t.getId(), auxFormat.format(t.getData()), t.getDescricao()});
  });
 }

 private void selecionar() {
  this.tarefa = BaseDados.RTarefa.getById((NitriteId) tbTarefas.getValueAt(tbTarefas.getSelectedRow(), 0));
  txData.setValue(auxFormat.format(this.tarefa.getData()));
  txDescricao.setText(this.tarefa.getDescricao());
 }

 private void excluir() {
  if (this.tarefa.getId() != null) {
   BaseDados.RTarefa.remove(tarefa);
   this.cancelar();
   this.recuperar();
   JOptionPane.showMessageDialog(this, "Registro Excluído");
  }
 }

 /**
  * Creates new form FrmMain
  */
 public FrmMain() {
  initComponents();
  this.recuperar();
 }

 /**
  * This method is called from within the constructor to initialize the form.
  * WARNING: Do NOT modify this code. The content of this method is always
  * regenerated by the Form Editor.
  */
 @SuppressWarnings("unchecked")
 // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
 private void initComponents() {

  jPanel1 = new javax.swing.JPanel();
  jLabel1 = new javax.swing.JLabel();
  jLabel2 = new javax.swing.JLabel();
  txData = new javax.swing.JFormattedTextField();
  txDescricao = new javax.swing.JTextField();
  jButton1 = new javax.swing.JButton();
  jButton2 = new javax.swing.JButton();
  jButton3 = new javax.swing.JButton();
  jPanel2 = new javax.swing.JPanel();
  jScrollPane1 = new javax.swing.JScrollPane();
  tbTarefas = new javax.swing.JTable();

  setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
  setTitle("Controle de Tarefas");

  jPanel1.setBackground(new java.awt.Color(204, 255, 255));

  jLabel1.setText("Data");

  jLabel2.setText("Descrição");

  try {
   txData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
  } catch (java.text.ParseException ex) {
   ex.printStackTrace();
  }

  jButton1.setText("Salvar");
  jButton1.addActionListener(new java.awt.event.ActionListener() {
   public void actionPerformed(java.awt.event.ActionEvent evt) {
    jButton1ActionPerformed(evt);
   }
  });

  jButton2.setText("Cancelar");
  jButton2.addActionListener(new java.awt.event.ActionListener() {
   public void actionPerformed(java.awt.event.ActionEvent evt) {
    jButton2ActionPerformed(evt);
   }
  });

  jButton3.setText("Excluir");
  jButton3.addActionListener(new java.awt.event.ActionListener() {
   public void actionPerformed(java.awt.event.ActionEvent evt) {
    jButton3ActionPerformed(evt);
   }
  });

  javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
  jPanel1.setLayout(jPanel1Layout);
  jPanel1Layout.setHorizontalGroup(
   jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
   .addGroup(jPanel1Layout.createSequentialGroup()
    .addContainerGap()
    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
     .addGroup(jPanel1Layout.createSequentialGroup()
      .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
       .addComponent(jLabel2)
       .addComponent(jLabel1))
      .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
      .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
       .addComponent(txData, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
       .addComponent(txDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)))
     .addGroup(jPanel1Layout.createSequentialGroup()
      .addComponent(jButton1)
      .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
      .addComponent(jButton2)
      .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
      .addComponent(jButton3)))
    .addContainerGap(69, Short.MAX_VALUE))
  );
  jPanel1Layout.setVerticalGroup(
   jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
   .addGroup(jPanel1Layout.createSequentialGroup()
    .addContainerGap()
    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
     .addComponent(jLabel1)
     .addComponent(txData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
     .addComponent(jLabel2)
     .addComponent(txDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
     .addComponent(jButton1)
     .addComponent(jButton2)
     .addComponent(jButton3))
    .addContainerGap(27, Short.MAX_VALUE))
  );

  jPanel2.setBackground(new java.awt.Color(255, 255, 204));

  tbTarefas.setModel(new javax.swing.table.DefaultTableModel(
   new Object [][] {

   },
   new String [] {
    "Id", "Data", "Descrição"
   }
  ) {
   boolean[] canEdit = new boolean [] {
    false, false, false
   };

   public boolean isCellEditable(int rowIndex, int columnIndex) {
    return canEdit [columnIndex];
   }
  });
  tbTarefas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
  tbTarefas.addMouseListener(new java.awt.event.MouseAdapter() {
   public void mouseClicked(java.awt.event.MouseEvent evt) {
    tbTarefasMouseClicked(evt);
   }
  });
  jScrollPane1.setViewportView(tbTarefas);
  if (tbTarefas.getColumnModel().getColumnCount() > 0) {
   tbTarefas.getColumnModel().getColumn(0).setResizable(false);
   tbTarefas.getColumnModel().getColumn(1).setResizable(false);
  }

  javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
  jPanel2.setLayout(jPanel2Layout);
  jPanel2Layout.setHorizontalGroup(
   jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
   .addGroup(jPanel2Layout.createSequentialGroup()
    .addContainerGap()
    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
    .addContainerGap())
  );
  jPanel2Layout.setVerticalGroup(
   jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
   .addGroup(jPanel2Layout.createSequentialGroup()
    .addContainerGap()
    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
    .addContainerGap())
  );

  javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
  getContentPane().setLayout(layout);
  layout.setHorizontalGroup(
   layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
   .addGroup(layout.createSequentialGroup()
    .addContainerGap()
    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
     .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
     .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    .addContainerGap())
  );
  layout.setVerticalGroup(
   layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
   .addGroup(layout.createSequentialGroup()
    .addContainerGap()
    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
  );

  pack();
  setLocationRelativeTo(null);
 }// </editor-fold>//GEN-END:initComponents

 private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
  this.salvar();
 }//GEN-LAST:event_jButton1ActionPerformed

 private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
  this.cancelar();
 }//GEN-LAST:event_jButton2ActionPerformed

 private void tbTarefasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbTarefasMouseClicked
  selecionar();
 }//GEN-LAST:event_tbTarefasMouseClicked

 private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
  excluir();
 }//GEN-LAST:event_jButton3ActionPerformed

 // Variables declaration - do not modify//GEN-BEGIN:variables
 private javax.swing.JButton jButton1;
 private javax.swing.JButton jButton2;
 private javax.swing.JButton jButton3;
 private javax.swing.JLabel jLabel1;
 private javax.swing.JLabel jLabel2;
 private javax.swing.JPanel jPanel1;
 private javax.swing.JPanel jPanel2;
 private javax.swing.JScrollPane jScrollPane1;
 private javax.swing.JTable tbTarefas;
 private javax.swing.JFormattedTextField txData;
 private javax.swing.JTextField txDescricao;
 // End of variables declaration//GEN-END:variables
}
